export const hostStats = {
  upcoming: 2,
  live: 1,
  drafts: 1,
  completed: 8,
  pendingRequests: 3,
  totalParticipants: 145,
};

export const hostAnalytics = {
  activitiesCreated: 12,
  activitiesCompleted: 8,
  totalParticipants: 145,
  averageAttendance: 14,
  savedActivities: 23,
};

export const hostActivities = [
  {
    id: 'h1',
    title: 'Morning Meditation Walk',
    type: 'experience',
    status: 'upcoming',
    coverImage: 'https://images.unsplash.com/photo-1545389336-cf0906944357?w=400',
    date: 'Jul 15, 2026',
    time: '7:00 AM',
    location: 'Riverside Park, Dubai',
    visibility: 'public',
    joinedMembers: 8,
    pendingRequests: 2,
    capacity: 20,
    category: 'Wellness',
  },
  {
    id: 'h2',
    title: 'Coffee & Connection',
    type: 'experience',
    status: 'live',
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    date: 'Jul 4, 2026',
    time: '9:00 AM',
    location: 'Downtown Café, Dubai',
    visibility: 'public',
    joinedMembers: 5,
    pendingRequests: 1,
    capacity: 12,
    category: 'Social',
    currentParticipants: 5,
    timeRemaining: '1h 15m left',
  },
  {
    id: 'h3',
    title: 'Art Therapy Workshop',
    type: 'experience',
    status: 'draft',
    coverImage: 'https://images.unsplash.com/photo-1513590204371-37633284c4f4?w=400',
    date: 'Not set',
    time: '',
    location: 'Not set',
    visibility: 'approval',
    joinedMembers: 0,
    pendingRequests: 0,
    capacity: 15,
    category: 'Creative',
  },
  {
    id: 'h4',
    title: 'Mindful Mornings Circle',
    type: 'circle',
    status: 'completed',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca97ce1626a?w=400',
    date: 'Jun 28, 2026',
    time: '6:30 AM',
    location: 'Community Center, Dubai',
    visibility: 'public',
    joinedMembers: 15,
    pendingRequests: 0,
    capacity: 15,
    category: 'Wellness',
  },
  {
    id: 'h5',
    title: 'Sunset Yoga Session',
    type: 'experience',
    status: 'completed',
    coverImage: 'https://images.unsplash.com/photo-1544367559-3b0d0c1f5a3f?w=400',
    date: 'Jun 20, 2026',
    time: '6:00 PM',
    location: 'Beachfront Park, Dubai',
    visibility: 'public',
    joinedMembers: 18,
    pendingRequests: 0,
    capacity: 20,
    category: 'Wellness',
  },
  {
    id: 'h6',
    title: 'Creative Souls Meetup',
    type: 'circle',
    status: 'cancelled',
    coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    date: 'Jun 15, 2026',
    time: '3:00 PM',
    location: 'Art Studio, Dubai',
    visibility: 'invite',
    joinedMembers: 3,
    pendingRequests: 0,
    capacity: 10,
    category: 'Creative',
  },
  {
    id: 'h7',
    title: 'Book Lovers Circle',
    type: 'circle',
    status: 'upcoming',
    coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    date: 'Jul 20, 2026',
    time: '5:00 PM',
    location: 'Central Library, Dubai',
    visibility: 'approval',
    joinedMembers: 6,
    pendingRequests: 3,
    capacity: 15,
    category: 'Learning',
  },
];

export const joinRequests = [
  {
    id: 'r1',
    activityId: 'h1',
    activityTitle: 'Morning Meditation Walk',
    memberName: 'Sarah Chen',
    memberAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    memberAge: 28,
    languages: ['English', 'Mandarin'],
    mutualInterests: ['Meditation', 'Yoga', 'Wellness'],
    verified: true,
    joinedDate: '2 days ago',
    bio: 'Meditation enthusiast looking to connect with like-minded people in the community.',
  },
  {
    id: 'r2',
    activityId: 'h1',
    activityTitle: 'Morning Meditation Walk',
    memberName: 'James Wilson',
    memberAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    memberAge: 32,
    languages: ['English', 'Arabic'],
    mutualInterests: ['Morning Walks', 'Wellness'],
    verified: true,
    joinedDate: '1 day ago',
    bio: 'Early riser who loves starting the day with a peaceful walk in nature.',
  },
  {
    id: 'r3',
    activityId: 'h7',
    activityTitle: 'Book Lovers Circle',
    memberName: 'Emma Rodriguez',
    memberAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    memberAge: 26,
    languages: ['English', 'Spanish'],
    mutualInterests: ['Reading', 'Social'],
    verified: false,
    joinedDate: '3 hours ago',
    bio: 'New to the city and excited to meet fellow book lovers.',
  },
];

export const categories = ['Wellness', 'Social', 'Creative', 'Fitness', 'Learning', 'Outdoor', 'Music', 'Food'];
export const moods = ['😌 Calm', '⚡ Energetic', '🎨 Creative', '📚 Focused', '😊 Happy', '🧘 Mindful', '🎉 Excited', '💬 Social'];
export const languagesList = ['English', 'Arabic', 'Spanish', 'French', 'German', 'Mandarin', 'Hindi', 'Portuguese'];
export const timezones = ['GMT+4 (Dubai)', 'GMT+0 (London)', 'GMT-5 (New York)', 'GMT+1 (Paris)', 'GMT+8 (Singapore)', 'GMT+5:30 (Mumbai)'];