// Master Country Dataset — single source of truth for all country references.
// ISO 3166-1 codes, dialing codes, regions, currency, flag, native name, primary timezone.
// Extensible: append entries to add territories. Keep sorted by English name.

export const COUNTRIES = [
  { key:'af', iso2:'AF', iso3:'AFG', name:'Afghanistan', native:'افغانستان', dialing:'+93', region:'Asia', subregion:'Southern Asia', currency:'AFN', flag:'🇦🇫', timezone:'Asia/Kabul' },
  { key:'al', iso2:'AL', iso3:'ALB', name:'Albania', native:'Shqipëria', dialing:'+355', region:'Europe', subregion:'Southern Europe', currency:'ALL', flag:'🇦🇱', timezone:'Europe/Tirane' },
  { key:'dz', iso2:'DZ', iso3:'DZA', name:'Algeria', native:'الجزائر', dialing:'+213', region:'Africa', subregion:'Northern Africa', currency:'DZD', flag:'🇩🇿', timezone:'Africa/Algiers' },
  { key:'ad', iso2:'AD', iso3:'AND', name:'Andorra', native:'Andorra', dialing:'+376', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇦🇩', timezone:'Europe/Andorra' },
  { key:'ao', iso2:'AO', iso3:'AGO', name:'Angola', native:'Angola', dialing:'+244', region:'Africa', subregion:'Middle Africa', currency:'AOA', flag:'🇦🇴', timezone:'Africa/Luanda' },
  { key:'ar', iso2:'AR', iso3:'ARG', name:'Argentina', native:'Argentina', dialing:'+54', region:'Americas', subregion:'South America', currency:'ARS', flag:'🇦🇷', timezone:'America/Argentina/Buenos_Aires' },
  { key:'am', iso2:'AM', iso3:'ARM', name:'Armenia', native:'Հայաստան', dialing:'+374', region:'Asia', subregion:'Western Asia', currency:'AMD', flag:'🇦🇲', timezone:'Asia/Yerevan' },
  { key:'au', iso2:'AU', iso3:'AUS', name:'Australia', native:'Australia', dialing:'+61', region:'Oceania', subregion:'Australia and New Zealand', currency:'AUD', flag:'🇦🇺', timezone:'Australia/Sydney' },
  { key:'at', iso2:'AT', iso3:'AUT', name:'Austria', native:'Österreich', dialing:'+43', region:'Europe', subregion:'Western Europe', currency:'EUR', flag:'🇦🇹', timezone:'Europe/Vienna' },
  { key:'az', iso2:'AZ', iso3:'AZE', name:'Azerbaijan', native:'Azərbaycan', dialing:'+994', region:'Asia', subregion:'Western Asia', currency:'AZN', flag:'🇦🇿', timezone:'Asia/Baku' },
  { key:'bh', iso2:'BH', iso3:'BHR', name:'Bahrain', native:'البحرين', dialing:'+973', region:'Asia', subregion:'Western Asia', currency:'BHD', flag:'🇧🇭', timezone:'Asia/Bahrain' },
  { key:'bd', iso2:'BD', iso3:'BGD', name:'Bangladesh', native:'বাংলাদেশ', dialing:'+880', region:'Asia', subregion:'Southern Asia', currency:'BDT', flag:'🇧🇩', timezone:'Asia/Dhaka' },
  { key:'by', iso2:'BY', iso3:'BLR', name:'Belarus', native:'Беларусь', dialing:'+375', region:'Europe', subregion:'Eastern Europe', currency:'BYN', flag:'🇧🇾', timezone:'Europe/Minsk' },
  { key:'be', iso2:'BE', iso3:'BEL', name:'Belgium', native:'België', dialing:'+32', region:'Europe', subregion:'Western Europe', currency:'EUR', flag:'🇧🇪', timezone:'Europe/Brussels' },
  { key:'bz', iso2:'BZ', iso3:'BLZ', name:'Belize', native:'Belize', dialing:'+501', region:'Americas', subregion:'Central America', currency:'BZD', flag:'🇧🇿', timezone:'America/Belize' },
  { key:'bj', iso2:'BJ', iso3:'BEN', name:'Benin', native:'Bénin', dialing:'+229', region:'Africa', subregion:'Western Africa', currency:'XOF', flag:'🇧🇯', timezone:'Africa/Porto-Novo' },
  { key:'bt', iso2:'BT', iso3:'BTN', name:'Bhutan', native:'འབྲུག', dialing:'+975', region:'Asia', subregion:'Southern Asia', currency:'BTN', flag:'🇧🇹', timezone:'Asia/Thimphu' },
  { key:'bo', iso2:'BO', iso3:'BOL', name:'Bolivia', native:'Bolivia', dialing:'+591', region:'Americas', subregion:'South America', currency:'BOB', flag:'🇧🇴', timezone:'America/La_Paz' },
  { key:'ba', iso2:'BA', iso3:'BIH', name:'Bosnia and Herzegovina', native:'Bosna i Hercegovina', dialing:'+387', region:'Europe', subregion:'Southern Europe', currency:'BAM', flag:'🇧🇦', timezone:'Europe/Sarajevo' },
  { key:'bw', iso2:'BW', iso3:'BWA', name:'Botswana', native:'Botswana', dialing:'+267', region:'Africa', subregion:'Southern Africa', currency:'BWP', flag:'🇧🇼', timezone:'Africa/Gaborone' },
  { key:'br', iso2:'BR', iso3:'BRA', name:'Brazil', native:'Brasil', dialing:'+55', region:'Americas', subregion:'South America', currency:'BRL', flag:'🇧🇷', timezone:'America/Sao_Paulo' },
  { key:'bn', iso2:'BN', iso3:'BRN', name:'Brunei', native:'Brunei', dialing:'+673', region:'Asia', subregion:'South-Eastern Asia', currency:'BND', flag:'🇧🇳', timezone:'Asia/Brunei' },
  { key:'bg', iso2:'BG', iso3:'BGR', name:'Bulgaria', native:'България', dialing:'+359', region:'Europe', subregion:'Eastern Europe', currency:'BGN', flag:'🇧🇬', timezone:'Europe/Sofia' },
  { key:'bf', iso2:'BF', iso3:'BFA', name:'Burkina Faso', native:'Burkina Faso', dialing:'+226', region:'Africa', subregion:'Western Africa', currency:'XOF', flag:'🇧🇫', timezone:'Africa/Ouagadougou' },
  { key:'kh', iso2:'KH', iso3:'KHM', name:'Cambodia', native:'កម្ពុជា', dialing:'+855', region:'Asia', subregion:'South-Eastern Asia', currency:'KHR', flag:'🇰🇭', timezone:'Asia/Phnom_Penh' },
  { key:'cm', iso2:'CM', iso3:'CMR', name:'Cameroon', native:'Cameroun', dialing:'+237', region:'Africa', subregion:'Middle Africa', currency:'XAF', flag:'🇨🇲', timezone:'Africa/Douala' },
  { key:'ca', iso2:'CA', iso3:'CAN', name:'Canada', native:'Canada', dialing:'+1', region:'Americas', subregion:'Northern America', currency:'CAD', flag:'🇨🇦', timezone:'America/Toronto' },
  { key:'cl', iso2:'CL', iso3:'CHL', name:'Chile', native:'Chile', dialing:'+56', region:'Americas', subregion:'South America', currency:'CLP', flag:'🇨🇱', timezone:'America/Santiago' },
  { key:'cn', iso2:'CN', iso3:'CHN', name:'China', native:'中国', dialing:'+86', region:'Asia', subregion:'Eastern Asia', currency:'CNY', flag:'🇨🇳', timezone:'Asia/Shanghai' },
  { key:'co', iso2:'CO', iso3:'COL', name:'Colombia', native:'Colombia', dialing:'+57', region:'Americas', subregion:'South America', currency:'COP', flag:'🇨🇴', timezone:'America/Bogota' },
  { key:'cr', iso2:'CR', iso3:'CRI', name:'Costa Rica', native:'Costa Rica', dialing:'+506', region:'Americas', subregion:'Central America', currency:'CRC', flag:'🇨🇷', timezone:'America/Costa_Rica' },
  { key:'hr', iso2:'HR', iso3:'HRV', name:'Croatia', native:'Hrvatska', dialing:'+385', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇭🇷', timezone:'Europe/Zagreb' },
  { key:'cu', iso2:'CU', iso3:'CUB', name:'Cuba', native:'Cuba', dialing:'+53', region:'Americas', subregion:'Caribbean', currency:'CUP', flag:'🇨🇺', timezone:'America/Havana' },
  { key:'cy', iso2:'CY', iso3:'CYP', name:'Cyprus', native:'Κύπρος', dialing:'+357', region:'Asia', subregion:'Western Asia', currency:'EUR', flag:'🇨🇾', timezone:'Asia/Nicosia' },
  { key:'cz', iso2:'CZ', iso3:'CZE', name:'Czechia', native:'Česko', dialing:'+420', region:'Europe', subregion:'Eastern Europe', currency:'CZK', flag:'🇨🇿', timezone:'Europe/Prague' },
  { key:'dk', iso2:'DK', iso3:'DNK', name:'Denmark', native:'Danmark', dialing:'+45', region:'Europe', subregion:'Northern Europe', currency:'DKK', flag:'🇩🇰', timezone:'Europe/Copenhagen' },
  { key:'dj', iso2:'DJ', iso3:'DJI', name:'Djibouti', native:'Djibouti', dialing:'+253', region:'Africa', subregion:'Eastern Africa', currency:'DJF', flag:'🇩🇯', timezone:'Africa/Djibouti' },
  { key:'do', iso2:'DO', iso3:'DOM', name:'Dominican Republic', native:'República Dominicana', dialing:'+1', region:'Americas', subregion:'Caribbean', currency:'DOP', flag:'🇩🇴', timezone:'America/Santo_Domingo' },
  { key:'ec', iso2:'EC', iso3:'ECU', name:'Ecuador', native:'Ecuador', dialing:'+593', region:'Americas', subregion:'South America', currency:'USD', flag:'🇪🇨', timezone:'America/Guayaquil' },
  { key:'eg', iso2:'EG', iso3:'EGY', name:'Egypt', native:'مصر', dialing:'+20', region:'Africa', subregion:'Northern Africa', currency:'EGP', flag:'🇪🇬', timezone:'Africa/Cairo' },
  { key:'sv', iso2:'SV', iso3:'SLV', name:'El Salvador', native:'El Salvador', dialing:'+503', region:'Americas', subregion:'Central America', currency:'USD', flag:'🇸🇻', timezone:'America/El_Salvador' },
  { key:'ee', iso2:'EE', iso3:'EST', name:'Estonia', native:'Eesti', dialing:'+372', region:'Europe', subregion:'Northern Europe', currency:'EUR', flag:'🇪🇪', timezone:'Europe/Tallinn' },
  { key:'sz', iso2:'SZ', iso3:'SWZ', name:'Eswatini', native:'eSwatini', dialing:'+268', region:'Africa', subregion:'Southern Africa', currency:'SZL', flag:'🇸🇿', timezone:'Africa/Mbabane' },
  { key:'et', iso2:'ET', iso3:'ETH', name:'Ethiopia', native:'ኢትዮጵያ', dialing:'+251', region:'Africa', subregion:'Eastern Africa', currency:'ETB', flag:'🇪🇹', timezone:'Africa/Addis_Ababa' },
  { key:'fj', iso2:'FJ', iso3:'FJI', name:'Fiji', native:'Fiji', dialing:'+679', region:'Oceania', subregion:'Melanesia', currency:'FJD', flag:'🇫🇯', timezone:'Pacific/Fiji' },
  { key:'fi', iso2:'FI', iso3:'FIN', name:'Finland', native:'Suomi', dialing:'+358', region:'Europe', subregion:'Northern Europe', currency:'EUR', flag:'🇫🇮', timezone:'Europe/Helsinki' },
  { key:'fr', iso2:'FR', iso3:'FRA', name:'France', native:'France', dialing:'+33', region:'Europe', subregion:'Western Europe', currency:'EUR', flag:'🇫🇷', timezone:'Europe/Paris' },
  { key:'ga', iso2:'GA', iso3:'GAB', name:'Gabon', native:'Gabon', dialing:'+241', region:'Africa', subregion:'Middle Africa', currency:'XAF', flag:'🇬🇦', timezone:'Africa/Libreville' },
  { key:'ge', iso2:'GE', iso3:'GEO', name:'Georgia', native:'საქართველო', dialing:'+995', region:'Asia', subregion:'Western Asia', currency:'GEL', flag:'🇬🇪', timezone:'Asia/Tbilisi' },
  { key:'de', iso2:'DE', iso3:'DEU', name:'Germany', native:'Deutschland', dialing:'+49', region:'Europe', subregion:'Western Europe', currency:'EUR', flag:'🇩🇪', timezone:'Europe/Berlin' },
  { key:'gh', iso2:'GH', iso3:'GHA', name:'Ghana', native:'Ghana', dialing:'+233', region:'Africa', subregion:'Western Africa', currency:'GHS', flag:'🇬🇭', timezone:'Africa/Accra' },
  { key:'gr', iso2:'GR', iso3:'GRC', name:'Greece', native:'Ελλάδα', dialing:'+30', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇬🇷', timezone:'Europe/Athens' },
  { key:'gt', iso2:'GT', iso3:'GTM', name:'Guatemala', native:'Guatemala', dialing:'+502', region:'Americas', subregion:'Central America', currency:'GTQ', flag:'🇬🇹', timezone:'America/Guatemala' },
  { key:'gn', iso2:'GN', iso3:'GIN', name:'Guinea', native:'Guinée', dialing:'+224', region:'Africa', subregion:'Western Africa', currency:'GNF', flag:'🇬🇳', timezone:'Africa/Conakry' },
  { key:'hk', iso2:'HK', iso3:'HKG', name:'Hong Kong', native:'香港', dialing:'+852', region:'Asia', subregion:'Eastern Asia', currency:'HKD', flag:'🇭🇰', timezone:'Asia/Hong_Kong' },
  { key:'hu', iso2:'HU', iso3:'HUN', name:'Hungary', native:'Magyarország', dialing:'+36', region:'Europe', subregion:'Eastern Europe', currency:'HUF', flag:'🇭🇺', timezone:'Europe/Budapest' },
  { key:'is', iso2:'IS', iso3:'ISL', name:'Iceland', native:'Ísland', dialing:'+354', region:'Europe', subregion:'Northern Europe', currency:'ISK', flag:'🇮🇸', timezone:'Atlantic/Reykjavik' },
  { key:'in', iso2:'IN', iso3:'IND', name:'India', native:'भारत', dialing:'+91', region:'Asia', subregion:'Southern Asia', currency:'INR', flag:'🇮🇳', timezone:'Asia/Kolkata' },
  { key:'id', iso2:'ID', iso3:'IDN', name:'Indonesia', native:'Indonesia', dialing:'+62', region:'Asia', subregion:'South-Eastern Asia', currency:'IDR', flag:'🇮🇩', timezone:'Asia/Jakarta' },
  { key:'ir', iso2:'IR', iso3:'IRN', name:'Iran', native:'ایران', dialing:'+98', region:'Asia', subregion:'Southern Asia', currency:'IRR', flag:'🇮🇷', timezone:'Asia/Tehran' },
  { key:'iq', iso2:'IQ', iso3:'IRQ', name:'Iraq', native:'العراق', dialing:'+964', region:'Asia', subregion:'Western Asia', currency:'IQD', flag:'🇮🇶', timezone:'Asia/Baghdad' },
  { key:'ie', iso2:'IE', iso3:'IRL', name:'Ireland', native:'Éire', dialing:'+353', region:'Europe', subregion:'Northern Europe', currency:'EUR', flag:'🇮🇪', timezone:'Europe/Dublin' },
  { key:'il', iso2:'IL', iso3:'ISR', name:'Israel', native:'ישראל', dialing:'+972', region:'Asia', subregion:'Western Asia', currency:'ILS', flag:'🇮🇱', timezone:'Asia/Jerusalem' },
  { key:'it', iso2:'IT', iso3:'ITA', name:'Italy', native:'Italia', dialing:'+39', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇮🇹', timezone:'Europe/Rome' },
  { key:'jp', iso2:'JP', iso3:'JPN', name:'Japan', native:'日本', dialing:'+81', region:'Asia', subregion:'Eastern Asia', currency:'JPY', flag:'🇯🇵', timezone:'Asia/Tokyo' },
  { key:'jo', iso2:'JO', iso3:'JOR', name:'Jordan', native:'الأردن', dialing:'+962', region:'Asia', subregion:'Western Asia', currency:'JOD', flag:'🇯🇴', timezone:'Asia/Amman' },
  { key:'kz', iso2:'KZ', iso3:'KAZ', name:'Kazakhstan', native:'Қазақстан', dialing:'+7', region:'Asia', subregion:'Central Asia', currency:'KZT', flag:'🇰🇿', timezone:'Asia/Almaty' },
  { key:'ke', iso2:'KE', iso3:'KEN', name:'Kenya', native:'Kenya', dialing:'+254', region:'Africa', subregion:'Eastern Africa', currency:'KES', flag:'🇰🇪', timezone:'Africa/Nairobi' },
  { key:'kw', iso2:'KW', iso3:'KWT', name:'Kuwait', native:'الكويت', dialing:'+965', region:'Asia', subregion:'Western Asia', currency:'KWD', flag:'🇰🇼', timezone:'Asia/Kuwait' },
  { key:'kg', iso2:'KG', iso3:'KGZ', name:'Kyrgyzstan', native:'Кыргызстан', dialing:'+996', region:'Asia', subregion:'Central Asia', currency:'KGS', flag:'🇰🇬', timezone:'Asia/Bishkek' },
  { key:'la', iso2:'LA', iso3:'LAO', name:'Laos', native:'ລາວ', dialing:'+856', region:'Asia', subregion:'South-Eastern Asia', currency:'LAK', flag:'🇱🇦', timezone:'Asia/Vientiane' },
  { key:'lv', iso2:'LV', iso3:'LVA', name:'Latvia', native:'Latvija', dialing:'+371', region:'Europe', subregion:'Northern Europe', currency:'EUR', flag:'🇱🇻', timezone:'Europe/Riga' },
  { key:'lb', iso2:'LB', iso3:'LBN', name:'Lebanon', native:'لبنان', dialing:'+961', region:'Asia', subregion:'Western Asia', currency:'LBP', flag:'🇱🇧', timezone:'Asia/Beirut' },
  { key:'ly', iso2:'LY', iso3:'LBY', name:'Libya', native:'ليبيا', dialing:'+218', region:'Africa', subregion:'Northern Africa', currency:'LYD', flag:'🇱🇾', timezone:'Africa/Tripoli' },
  { key:'lt', iso2:'LT', iso3:'LTU', name:'Lithuania', native:'Lietuva', dialing:'+370', region:'Europe', subregion:'Northern Europe', currency:'EUR', flag:'🇱🇹', timezone:'Europe/Vilnius' },
  { key:'lu', iso2:'LU', iso3:'LUX', name:'Luxembourg', native:'Luxembourg', dialing:'+352', region:'Europe', subregion:'Western Europe', currency:'EUR', flag:'🇱🇺', timezone:'Europe/Luxembourg' },
  { key:'mo', iso2:'MO', iso3:'MAC', name:'Macao', native:'澳門', dialing:'+853', region:'Asia', subregion:'Eastern Asia', currency:'MOP', flag:'🇲🇴', timezone:'Asia/Macau' },
  { key:'mg', iso2:'MG', iso3:'MDG', name:'Madagascar', native:'Madagasikara', dialing:'+261', region:'Africa', subregion:'Eastern Africa', currency:'MGA', flag:'🇲🇬', timezone:'Indian/Antananarivo' },
  { key:'my', iso2:'MY', iso3:'MYS', name:'Malaysia', native:'Malaysia', dialing:'+60', region:'Asia', subregion:'South-Eastern Asia', currency:'MYR', flag:'🇲🇾', timezone:'Asia/Kuala_Lumpur' },
  { key:'mv', iso2:'MV', iso3:'MDV', name:'Maldives', native:'Maldives', dialing:'+960', region:'Asia', subregion:'Southern Asia', currency:'MVR', flag:'🇲🇻', timezone:'Indian/Maldives' },
  { key:'ml', iso2:'ML', iso3:'MLI', name:'Mali', native:'Mali', dialing:'+223', region:'Africa', subregion:'Western Africa', currency:'XOF', flag:'🇲🇱', timezone:'Africa/Bamako' },
  { key:'mt', iso2:'MT', iso3:'MLT', name:'Malta', native:'Malta', dialing:'+356', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇲🇹', timezone:'Europe/Malta' },
  { key:'mr', iso2:'MR', iso3:'MRT', name:'Mauritania', native:'موريتانيا', dialing:'+222', region:'Africa', subregion:'Western Africa', currency:'MRU', flag:'🇲🇷', timezone:'Africa/Nouakchott' },
  { key:'mu', iso2:'MU', iso3:'MUS', name:'Mauritius', native:'Maurice', dialing:'+230', region:'Africa', subregion:'Eastern Africa', currency:'MUR', flag:'🇲🇺', timezone:'Indian/Mauritius' },
  { key:'mx', iso2:'MX', iso3:'MEX', name:'Mexico', native:'México', dialing:'+52', region:'Americas', subregion:'North America', currency:'MXN', flag:'🇲🇽', timezone:'America/Mexico_City' },
  { key:'md', iso2:'MD', iso3:'MDA', name:'Moldova', native:'Moldova', dialing:'+373', region:'Europe', subregion:'Eastern Europe', currency:'MDL', flag:'🇲🇩', timezone:'Europe/Chisinau' },
  { key:'mc', iso2:'MC', iso3:'MCO', name:'Monaco', native:'Monaco', dialing:'+377', region:'Europe', subregion:'Western Europe', currency:'EUR', flag:'🇲🇨', timezone:'Europe/Monaco' },
  { key:'mn', iso2:'MN', iso3:'MNG', name:'Mongolia', native:'Монгол', dialing:'+976', region:'Asia', subregion:'Eastern Asia', currency:'MNT', flag:'🇲🇳', timezone:'Asia/Ulaanbaatar' },
  { key:'ma', iso2:'MA', iso3:'MAR', name:'Morocco', native:'المغرب', dialing:'+212', region:'Africa', subregion:'Northern Africa', currency:'MAD', flag:'🇲🇦', timezone:'Africa/Casablanca' },
  { key:'mz', iso2:'MZ', iso3:'MOZ', name:'Mozambique', native:'Moçambique', dialing:'+258', region:'Africa', subregion:'Eastern Africa', currency:'MZN', flag:'🇲🇿', timezone:'Africa/Maputo' },
  { key:'mm', iso2:'MM', iso3:'MMR', name:'Myanmar', native:'မြန်မာ', dialing:'+95', region:'Asia', subregion:'South-Eastern Asia', currency:'MMK', flag:'🇲🇲', timezone:'Asia/Yangon' },
  { key:'na', iso2:'NA', iso3:'NAM', name:'Namibia', native:'Namibia', dialing:'+264', region:'Africa', subregion:'Southern Africa', currency:'NAD', flag:'🇳🇦', timezone:'Africa/Windhoek' },
  { key:'np', iso2:'NP', iso3:'NPL', name:'Nepal', native:'नेपाल', dialing:'+977', region:'Asia', subregion:'Southern Asia', currency:'NPR', flag:'🇳🇵', timezone:'Asia/Kathmandu' },
  { key:'nl', iso2:'NL', iso3:'NLD', name:'Netherlands', native:'Nederland', dialing:'+31', region:'Europe', subregion:'Western Europe', currency:'EUR', flag:'🇳🇱', timezone:'Europe/Amsterdam' },
  { key:'nz', iso2:'NZ', iso3:'NZL', name:'New Zealand', native:'Aotearoa', dialing:'+64', region:'Oceania', subregion:'Australia and New Zealand', currency:'NZD', flag:'🇳🇿', timezone:'Pacific/Auckland' },
  { key:'ni', iso2:'NI', iso3:'NIC', name:'Nicaragua', native:'Nicaragua', dialing:'+505', region:'Americas', subregion:'Central America', currency:'NIO', flag:'🇳🇮', timezone:'America/Managua' },
  { key:'ne', iso2:'NE', iso3:'NER', name:'Niger', native:'Niger', dialing:'+227', region:'Africa', subregion:'Western Africa', currency:'XOF', flag:'🇳🇪', timezone:'Africa/Niamey' },
  { key:'ng', iso2:'NG', iso3:'NGA', name:'Nigeria', native:'Nigeria', dialing:'+234', region:'Africa', subregion:'Western Africa', currency:'NGN', flag:'🇳🇬', timezone:'Africa/Lagos' },
  { key:'kp', iso2:'KP', iso3:'PRK', name:'North Korea', native:'조선', dialing:'+850', region:'Asia', subregion:'Eastern Asia', currency:'KPW', flag:'🇰🇵', timezone:'Asia/Pyongyang' },
  { key:'mk', iso2:'MK', iso3:'MKD', name:'North Macedonia', native:'Северна Македонија', dialing:'+389', region:'Europe', subregion:'Southern Europe', currency:'MKD', flag:'🇲🇰', timezone:'Europe/Skopje' },
  { key:'no', iso2:'NO', iso3:'NOR', name:'Norway', native:'Norge', dialing:'+47', region:'Europe', subregion:'Northern Europe', currency:'NOK', flag:'🇳🇴', timezone:'Europe/Oslo' },
  { key:'om', iso2:'OM', iso3:'OMN', name:'Oman', native:'عُمان', dialing:'+968', region:'Asia', subregion:'Western Asia', currency:'OMR', flag:'🇴🇲', timezone:'Asia/Muscat' },
  { key:'pk', iso2:'PK', iso3:'PAK', name:'Pakistan', native:'پاکستان', dialing:'+92', region:'Asia', subregion:'Southern Asia', currency:'PKR', flag:'🇵🇰', timezone:'Asia/Karachi' },
  { key:'ps', iso2:'PS', iso3:'PSE', name:'Palestine', native:'فلسطين', dialing:'+970', region:'Asia', subregion:'Western Asia', currency:'ILS', flag:'🇵🇸', timezone:'Asia/Gaza' },
  { key:'pa', iso2:'PA', iso3:'PAN', name:'Panama', native:'Panamá', dialing:'+507', region:'Americas', subregion:'Central America', currency:'USD', flag:'🇵🇦', timezone:'America/Panama' },
  { key:'py', iso2:'PY', iso3:'PRY', name:'Paraguay', native:'Paraguay', dialing:'+595', region:'Americas', subregion:'South America', currency:'PYG', flag:'🇵🇾', timezone:'America/Asuncion' },
  { key:'pe', iso2:'PE', iso3:'PER', name:'Peru', native:'Perú', dialing:'+51', region:'Americas', subregion:'South America', currency:'PEN', flag:'🇵🇪', timezone:'America/Lima' },
  { key:'ph', iso2:'PH', iso3:'PHL', name:'Philippines', native:'Pilipinas', dialing:'+63', region:'Asia', subregion:'South-Eastern Asia', currency:'PHP', flag:'🇵🇭', timezone:'Asia/Manila' },
  { key:'pl', iso2:'PL', iso3:'POL', name:'Poland', native:'Polska', dialing:'+48', region:'Europe', subregion:'Eastern Europe', currency:'PLN', flag:'🇵🇱', timezone:'Europe/Warsaw' },
  { key:'pt', iso2:'PT', iso3:'PRT', name:'Portugal', native:'Portugal', dialing:'+351', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇵🇹', timezone:'Europe/Lisbon' },
  { key:'qa', iso2:'QA', iso3:'QAT', name:'Qatar', native:'قطر', dialing:'+974', region:'Asia', subregion:'Western Asia', currency:'QAR', flag:'🇶🇦', timezone:'Asia/Qatar' },
  { key:'ro', iso2:'RO', iso3:'ROU', name:'Romania', native:'România', dialing:'+40', region:'Europe', subregion:'Eastern Europe', currency:'RON', flag:'🇷🇴', timezone:'Europe/Bucharest' },
  { key:'ru', iso2:'RU', iso3:'RUS', name:'Russia', native:'Россия', dialing:'+7', region:'Europe', subregion:'Eastern Europe', currency:'RUB', flag:'🇷🇺', timezone:'Europe/Moscow' },
  { key:'rw', iso2:'RW', iso3:'RWA', name:'Rwanda', native:'Rwanda', dialing:'+250', region:'Africa', subregion:'Eastern Africa', currency:'RWF', flag:'🇷🇼', timezone:'Africa/Kigali' },
  { key:'sa', iso2:'SA', iso3:'SAU', name:'Saudi Arabia', native:'السعودية', dialing:'+966', region:'Asia', subregion:'Western Asia', currency:'SAR', flag:'🇸🇦', timezone:'Asia/Riyadh' },
  { key:'sn', iso2:'SN', iso3:'SEN', name:'Senegal', native:'Sénégal', dialing:'+221', region:'Africa', subregion:'Western Africa', currency:'XOF', flag:'🇸🇳', timezone:'Africa/Dakar' },
  { key:'rs', iso2:'RS', iso3:'SRB', name:'Serbia', native:'Србија', dialing:'+381', region:'Europe', subregion:'Southern Europe', currency:'RSD', flag:'🇷🇸', timezone:'Europe/Belgrade' },
  { key:'sg', iso2:'SG', iso3:'SGP', name:'Singapore', native:'Singapore', dialing:'+65', region:'Asia', subregion:'South-Eastern Asia', currency:'SGD', flag:'🇸🇬', timezone:'Asia/Singapore' },
  { key:'sk', iso2:'SK', iso3:'SVK', name:'Slovakia', native:'Slovensko', dialing:'+421', region:'Europe', subregion:'Eastern Europe', currency:'EUR', flag:'🇸🇰', timezone:'Europe/Bratislava' },
  { key:'si', iso2:'SI', iso3:'SVN', name:'Slovenia', native:'Slovenija', dialing:'+386', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇸🇮', timezone:'Europe/Ljubljana' },
  { key:'so', iso2:'SO', iso3:'SOM', name:'Somalia', native:'Soomaaliya', dialing:'+252', region:'Africa', subregion:'Eastern Africa', currency:'SOS', flag:'🇸🇴', timezone:'Africa/Mogadishu' },
  { key:'za', iso2:'ZA', iso3:'ZAF', name:'South Africa', native:'South Africa', dialing:'+27', region:'Africa', subregion:'Southern Africa', currency:'ZAR', flag:'🇿🇦', timezone:'Africa/Johannesburg' },
  { key:'kr', iso2:'KR', iso3:'KOR', name:'South Korea', native:'대한민국', dialing:'+82', region:'Asia', subregion:'Eastern Asia', currency:'KRW', flag:'🇰🇷', timezone:'Asia/Seoul' },
  { key:'es', iso2:'ES', iso3:'ESP', name:'Spain', native:'España', dialing:'+34', region:'Europe', subregion:'Southern Europe', currency:'EUR', flag:'🇪🇸', timezone:'Europe/Madrid' },
  { key:'lk', iso2:'LK', iso3:'LKA', name:'Sri Lanka', native:'ශ්‍රී ලංකාව', dialing:'+94', region:'Asia', subregion:'Southern Asia', currency:'LKR', flag:'🇱🇰', timezone:'Asia/Colombo' },
  { key:'sd', iso2:'SD', iso3:'SDN', name:'Sudan', native:'السودان', dialing:'+249', region:'Africa', subregion:'Northern Africa', currency:'SDG', flag:'🇸🇩', timezone:'Africa/Khartoum' },
  { key:'se', iso2:'SE', iso3:'SWE', name:'Sweden', native:'Sverige', dialing:'+46', region:'Europe', subregion:'Northern Europe', currency:'SEK', flag:'🇸🇪', timezone:'Europe/Stockholm' },
  { key:'ch', iso2:'CH', iso3:'CHE', name:'Switzerland', native:'Schweiz', dialing:'+41', region:'Europe', subregion:'Western Europe', currency:'CHF', flag:'🇨🇭', timezone:'Europe/Zurich' },
  { key:'sy', iso2:'SY', iso3:'SYR', name:'Syria', native:'سوريا', dialing:'+963', region:'Asia', subregion:'Western Asia', currency:'SYP', flag:'🇸🇾', timezone:'Asia/Damascus' },
  { key:'tw', iso2:'TW', iso3:'TWN', name:'Taiwan', native:'臺灣', dialing:'+886', region:'Asia', subregion:'Eastern Asia', currency:'TWD', flag:'🇹🇼', timezone:'Asia/Taipei' },
  { key:'tj', iso2:'TJ', iso3:'TJK', name:'Tajikistan', native:'Тоҷикистон', dialing:'+992', region:'Asia', subregion:'Central Asia', currency:'TJS', flag:'🇹🇯', timezone:'Asia/Dushanbe' },
  { key:'tz', iso2:'TZ', iso3:'TZA', name:'Tanzania', native:'Tanzania', dialing:'+255', region:'Africa', subregion:'Eastern Africa', currency:'TZS', flag:'🇹🇿', timezone:'Africa/Dar_es_Salaam' },
  { key:'th', iso2:'TH', iso3:'THA', name:'Thailand', native:'ไทย', dialing:'+66', region:'Asia', subregion:'South-Eastern Asia', currency:'THB', flag:'🇹🇭', timezone:'Asia/Bangkok' },
  { key:'tn', iso2:'TN', iso3:'TUN', name:'Tunisia', native:'تونس', dialing:'+216', region:'Africa', subregion:'Northern Africa', currency:'TND', flag:'🇹🇳', timezone:'Africa/Tunis' },
  { key:'tr', iso2:'TR', iso3:'TUR', name:'Turkey', native:'Türkiye', dialing:'+90', region:'Asia', subregion:'Western Asia', currency:'TRY', flag:'🇹🇷', timezone:'Europe/Istanbul' },
  { key:'tm', iso2:'TM', iso3:'TKM', name:'Turkmenistan', native:'Türkmenistan', dialing:'+993', region:'Asia', subregion:'Central Asia', currency:'TMT', flag:'🇹🇲', timezone:'Asia/Ashgabat' },
  { key:'ug', iso2:'UG', iso3:'UGA', name:'Uganda', native:'Uganda', dialing:'+256', region:'Africa', subregion:'Eastern Africa', currency:'UGX', flag:'🇺🇬', timezone:'Africa/Kampala' },
  { key:'ua', iso2:'UA', iso3:'UKR', name:'Ukraine', native:'Україна', dialing:'+380', region:'Europe', subregion:'Eastern Europe', currency:'UAH', flag:'🇺🇦', timezone:'Europe/Kyiv' },
  { key:'ae', iso2:'AE', iso3:'ARE', name:'United Arab Emirates', native:'الإمارات', dialing:'+971', region:'Asia', subregion:'Western Asia', currency:'AED', flag:'🇦🇪', timezone:'Asia/Dubai' },
  { key:'gb', iso2:'GB', iso3:'GBR', name:'United Kingdom', native:'United Kingdom', dialing:'+44', region:'Europe', subregion:'Northern Europe', currency:'GBP', flag:'🇬🇧', timezone:'Europe/London' },
  { key:'us', iso2:'US', iso3:'USA', name:'United States', native:'United States', dialing:'+1', region:'Americas', subregion:'Northern America', currency:'USD', flag:'🇺🇸', timezone:'America/New_York' },
  { key:'uy', iso2:'UY', iso3:'URY', name:'Uruguay', native:'Uruguay', dialing:'+598', region:'Americas', subregion:'South America', currency:'UYU', flag:'🇺🇾', timezone:'America/Montevideo' },
  { key:'uz', iso2:'UZ', iso3:'UZB', name:'Uzbekistan', native:'Oʻzbekiston', dialing:'+998', region:'Asia', subregion:'Central Asia', currency:'UZS', flag:'🇺🇿', timezone:'Asia/Tashkent' },
  { key:'ve', iso2:'VE', iso3:'VEN', name:'Venezuela', native:'Venezuela', dialing:'+58', region:'Americas', subregion:'South America', currency:'VES', flag:'🇻🇪', timezone:'America/Caracas' },
  { key:'vn', iso2:'VN', iso3:'VNM', name:'Vietnam', native:'Việt Nam', dialing:'+84', region:'Asia', subregion:'South-Eastern Asia', currency:'VND', flag:'🇻🇳', timezone:'Asia/Ho_Chi_Minh' },
  { key:'ye', iso2:'YE', iso3:'YEM', name:'Yemen', native:'اليمن', dialing:'+967', region:'Asia', subregion:'Western Asia', currency:'YER', flag:'🇾🇪', timezone:'Asia/Aden' },
  { key:'zm', iso2:'ZM', iso3:'ZMB', name:'Zambia', native:'Zambia', dialing:'+260', region:'Africa', subregion:'Eastern Africa', currency:'ZMW', flag:'🇿🇲', timezone:'Africa/Lusaka' },
  { key:'zw', iso2:'ZW', iso3:'ZWE', name:'Zimbabwe', native:'Zimbabwe', dialing:'+263', region:'Africa', subregion:'Eastern Africa', currency:'ZWL', flag:'🇿🇼', timezone:'Africa/Harare' },
];

export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.key, c]));
export const REGIONS = [...new Set(COUNTRIES.map(c => c.region))].sort();
export const SUBREGIONS = [...new Set(COUNTRIES.map(c => c.subregion))].sort();