// Master Experience Types Dataset — canonical activity categories for experiences & circles.
// Stable keys referenced by Experience.category and member preferred experience types.

export const EXPERIENCE_TYPES = [
  { key:'coffee_meetup', label:'Coffee Meetup' },
  { key:'breakfast', label:'Breakfast' },
  { key:'lunch', label:'Lunch' },
  { key:'dinner', label:'Dinner' },
  { key:'brunch', label:'Brunch' },
  { key:'walking', label:'Walking' },
  { key:'hiking', label:'Hiking' },
  { key:'running', label:'Running' },
  { key:'cycling', label:'Cycling' },
  { key:'gym_session', label:'Gym Session' },
  { key:'padel_match', label:'Padel Match' },
  { key:'football_match', label:'Football Match' },
  { key:'basketball_game', label:'Basketball Game' },
  { key:'volleyball', label:'Volleyball' },
  { key:'swimming', label:'Swimming' },
  { key:'beach_day', label:'Beach Day' },
  { key:'camping', label:'Camping' },
  { key:'road_trip', label:'Road Trip' },
  { key:'movie_night', label:'Movie Night' },
  { key:'board_games', label:'Board Games' },
  { key:'escape_room', label:'Escape Room' },
  { key:'bowling', label:'Bowling' },
  { key:'arcade', label:'Arcade' },
  { key:'museum_visit', label:'Museum Visit' },
  { key:'art_gallery', label:'Art Gallery' },
  { key:'live_music', label:'Live Music' },
  { key:'concert', label:'Concert' },
  { key:'festival', label:'Festival' },
  { key:'cooking_class', label:'Cooking Class' },
  { key:'language_exchange', label:'Language Exchange' },
  { key:'networking_event', label:'Networking Event' },
  { key:'book_club', label:'Book Club' },
  { key:'photography_walk', label:'Photography Walk' },
  { key:'yoga_class', label:'Yoga Class' },
  { key:'meditation_session', label:'Meditation Session' },
  { key:'volunteering', label:'Volunteering' },
  { key:'business_meetup', label:'Business Meetup' },
  { key:'startup_meetup', label:'Startup Meetup' },
  { key:'family_picnic', label:'Family Picnic' },
  { key:'pet_walk', label:'Pet Walk' },
  { key:'travel_group', label:'Travel Group' },
  { key:'sightseeing', label:'Sightseeing' },
  { key:'desert_safari', label:'Desert Safari' },
  { key:'kayaking', label:'Kayaking' },
  { key:'paddleboarding', label:'Paddleboarding' },
  { key:'sailing', label:'Sailing' },
  { key:'fishing', label:'Fishing' },
  { key:'shopping', label:'Shopping' },
  { key:'spa_day', label:'Spa Day' },
  { key:'cultural_event', label:'Cultural Event' },
  { key:'comedy_show', label:'Comedy Show' },
  { key:'dance_class', label:'Dance Class' },
  { key:'fitness_challenge', label:'Fitness Challenge' },
  { key:'wine_tasting', label:'Wine Tasting' },
  { key:'tea_gathering', label:'Tea Gathering' },
  { key:'creative_workshop', label:'Creative Workshop' },
  { key:'charity_event', label:'Charity Event' },
  { key:'campfire', label:'Campfire' },
  { key:'star_party', label:'Stargazing Meetup' },
  { key:'food_tour', label:'Food Tour' },
  { key:'pottery_class', label:'Pottery Class' },
  { key:'painting_class', label:'Painting Class' },
  { key:'amusement_park', label:'Amusement Park' },
  { key:'horse_riding', label:'Horse Riding' },
  { key:'skiing_trip', label:'Skiing Trip' },
  { key:'kids_playdate', label:'Kids Playdate' },
  { key:'faith_gathering', label:'Faith Gathering' },
  { key:'wellness_retreat', label:'Wellness Retreat' },
];

export const EXPERIENCE_TYPE_MAP = Object.fromEntries(EXPERIENCE_TYPES.map((e) => [e.key, e]));