// Master Language Dataset — ISO 639-1/2, English + native names, writing direction.
// Source of truth for all language references across the platform.

export const LANGUAGES = [
  { key:'en', iso639_1:'en', iso639_2:'eng', name:'English', native:'English', direction:'ltr' },
  { key:'ar', iso639_1:'ar', iso639_2:'ara', name:'Arabic', native:'العربية', direction:'rtl' },
  { key:'zh', iso639_1:'zh', iso639_2:'zho', name:'Chinese', native:'中文', direction:'ltr' },
  { key:'es', iso639_1:'es', iso639_2:'spa', name:'Spanish', native:'Español', direction:'ltr' },
  { key:'fr', iso639_1:'fr', iso639_2:'fra', name:'French', native:'Français', direction:'ltr' },
  { key:'de', iso639_1:'de', iso639_2:'deu', name:'German', native:'Deutsch', direction:'ltr' },
  { key:'it', iso639_1:'it', iso639_2:'ita', name:'Italian', native:'Italiano', direction:'ltr' },
  { key:'pt', iso639_1:'pt', iso639_2:'por', name:'Portuguese', native:'Português', direction:'ltr' },
  { key:'ru', iso639_1:'ru', iso639_2:'rus', name:'Russian', native:'Русский', direction:'ltr' },
  { key:'ja', iso639_1:'ja', iso639_2:'jpn', name:'Japanese', native:'日本語', direction:'ltr' },
  { key:'ko', iso639_1:'ko', iso639_2:'kor', name:'Korean', native:'한국어', direction:'ltr' },
  { key:'hi', iso639_1:'hi', iso639_2:'hin', name:'Hindi', native:'हिन्दी', direction:'ltr' },
  { key:'bn', iso639_1:'bn', iso639_2:'ben', name:'Bengali', native:'বাংলা', direction:'ltr' },
  { key:'ur', iso639_1:'ur', iso639_2:'urd', name:'Urdu', native:'اردو', direction:'rtl' },
  { key:'fa', iso639_1:'fa', iso639_2:'fas', name:'Persian', native:'فارسی', direction:'rtl' },
  { key:'tr', iso639_1:'tr', iso639_2:'tur', name:'Turkish', native:'Türkçe', direction:'ltr' },
  { key:'nl', iso639_1:'nl', iso639_2:'nld', name:'Dutch', native:'Nederlands', direction:'ltr' },
  { key:'pl', iso639_1:'pl', iso639_2:'pol', name:'Polish', native:'Polski', direction:'ltr' },
  { key:'uk', iso639_1:'uk', iso639_2:'ukr', name:'Ukrainian', native:'Українська', direction:'ltr' },
  { key:'sv', iso639_1:'sv', iso639_2:'swe', name:'Swedish', native:'Svenska', direction:'ltr' },
  { key:'no', iso639_1:'no', iso639_2:'nor', name:'Norwegian', native:'Norsk', direction:'ltr' },
  { key:'da', iso639_1:'da', iso639_2:'dan', name:'Danish', native:'Dansk', direction:'ltr' },
  { key:'fi', iso639_1:'fi', iso639_2:'fin', name:'Finnish', native:'Suomi', direction:'ltr' },
  { key:'cs', iso639_1:'cs', iso639_2:'ces', name:'Czech', native:'Čeština', direction:'ltr' },
  { key:'sk', iso639_1:'sk', iso639_2:'slk', name:'Slovak', native:'Slovenčina', direction:'ltr' },
  { key:'hu', iso639_1:'hu', iso639_2:'hun', name:'Hungarian', native:'Magyar', direction:'ltr' },
  { key:'ro', iso639_1:'ro', iso639_2:'ron', name:'Romanian', native:'Română', direction:'ltr' },
  { key:'bg', iso639_1:'bg', iso639_2:'bul', name:'Bulgarian', native:'Български', direction:'ltr' },
  { key:'hr', iso639_1:'hr', iso639_2:'hrv', name:'Croatian', native:'Hrvatski', direction:'ltr' },
  { key:'sr', iso639_1:'sr', iso639_2:'srp', name:'Serbian', native:'Српски', direction:'ltr' },
  { key:'sl', iso639_1:'sl', iso639_2:'slv', name:'Slovenian', native:'Slovenščina', direction:'ltr' },
  { key:'el', iso639_1:'el', iso639_2:'ell', name:'Greek', native:'Ελληνικά', direction:'ltr' },
  { key:'he', iso639_1:'he', iso639_2:'heb', name:'Hebrew', native:'עברית', direction:'rtl' },
  { key:'th', iso639_1:'th', iso639_2:'tha', name:'Thai', native:'ไทย', direction:'ltr' },
  { key:'vi', iso639_1:'vi', iso639_2:'vie', name:'Vietnamese', native:'Tiếng Việt', direction:'ltr' },
  { key:'id', iso639_1:'id', iso639_2:'ind', name:'Indonesian', native:'Bahasa Indonesia', direction:'ltr' },
  { key:'ms', iso639_1:'ms', iso639_2:'msa', name:'Malay', native:'Bahasa Melayu', direction:'ltr' },
  { key:'tl', iso639_1:'tl', iso639_2:'tgl', name:'Filipino', native:'Filipino', direction:'ltr' },
  { key:'sw', iso639_1:'sw', iso639_2:'swa', name:'Swahili', native:'Kiswahili', direction:'ltr' },
  { key:'am', iso639_1:'am', iso639_2:'amh', name:'Amharic', native:'አማርኛ', direction:'ltr' },
  { key:'ha', iso639_1:'ha', iso639_2:'hau', name:'Hausa', native:'Hausa', direction:'ltr' },
  { key:'yo', iso639_1:'yo', iso639_2:'yor', name:'Yoruba', native:'Yorùbá', direction:'ltr' },
  { key:'zu', iso639_1:'zu', iso639_2:'zul', name:'Zulu', native:'isiZulu', direction:'ltr' },
  { key:'af', iso639_1:'af', iso639_2:'afr', name:'Afrikaans', native:'Afrikaans', direction:'ltr' },
  { key:'so', iso639_1:'so', iso639_2:'som', name:'Somali', native:'Soomaali', direction:'ltr' },
  { key:'ps', iso639_1:'ps', iso639_2:'pus', name:'Pashto', native:'پښتو', direction:'rtl' },
  { key:'ku', iso639_1:'ku', iso639_2:'kur', name:'Kurdish', native:'Kurdî', direction:'rtl' },
  { key:'az', iso639_1:'az', iso639_2:'aze', name:'Azerbaijani', native:'Azərbaycan', direction:'ltr' },
  { key:'kk', iso639_1:'kk', iso639_2:'kaz', name:'Kazakh', native:'Қазақ', direction:'ltr' },
  { key:'uz', iso639_1:'uz', iso639_2:'uzb', name:'Uzbek', native:'Oʻzbek', direction:'ltr' },
  { key:'ky', iso639_1:'ky', iso639_2:'kir', name:'Kyrgyz', native:'Кыргызча', direction:'ltr' },
  { key:'tg', iso639_1:'tg', iso639_2:'tgk', name:'Tajik', native:'Тоҷикӣ', direction:'ltr' },
  { key:'tm', iso639_1:'tm', iso639_2:'tuk', name:'Turkmen', native:'Türkmen', direction:'ltr' },
  { key:'hy', iso639_1:'hy', iso639_2:'hye', name:'Armenian', native:'Հայերեն', direction:'ltr' },
  { key:'ka', iso639_1:'ka', iso639_2:'kat', name:'Georgian', native:'ქართული', direction:'ltr' },
  { key:'ta', iso639_1:'ta', iso639_2:'tam', name:'Tamil', native:'தமிழ்', direction:'ltr' },
  { key:'te', iso639_1:'te', iso639_2:'tel', name:'Telugu', native:'తెలుగు', direction:'ltr' },
  { key:'ml', iso639_1:'ml', iso639_2:'mal', name:'Malayalam', native:'മലയാളം', direction:'ltr' },
  { key:'kn', iso639_1:'kn', iso639_2:'kan', name:'Kannada', native:'ಕನ್ನಡ', direction:'ltr' },
  { key:'mr', iso639_1:'mr', iso639_2:'mar', name:'Marathi', native:'मराठी', direction:'ltr' },
  { key:'gu', iso639_1:'gu', iso639_2:'guj', name:'Gujarati', native:'ગુજરાતી', direction:'ltr' },
  { key:'pa', iso639_1:'pa', iso639_2:'pan', name:'Punjabi', native:'ਪੰਜਾਬੀ', direction:'ltr' },
  { key:'ne', iso639_1:'ne', iso639_2:'nep', name:'Nepali', native:'नेपाली', direction:'ltr' },
  { key:'si', iso639_1:'si', iso639_2:'sin', name:'Sinhala', native:'සිංහල', direction:'ltr' },
  { key:'my', iso639_1:'my', iso639_2:'mya', name:'Burmese', native:'မြန်မာ', direction:'ltr' },
  { key:'km', iso639_1:'km', iso639_2:'khm', name:'Khmer', native:'ខ្មែរ', direction:'ltr' },
  { key:'lo', iso639_1:'lo', iso639_2:'lao', name:'Lao', native:'ລາວ', direction:'ltr' },
  { key:'mn', iso639_1:'mn', iso639_2:'mon', name:'Mongolian', native:'Монгол', direction:'ltr' },
  { key:'et', iso639_1:'et', iso639_2:'est', name:'Estonian', native:'Eesti', direction:'ltr' },
  { key:'lv', iso639_1:'lv', iso639_2:'lav', name:'Latvian', native:'Latviešu', direction:'ltr' },
  { key:'lt', iso639_1:'lt', iso639_2:'lit', name:'Lithuanian', native:'Lietuvių', direction:'ltr' },
  { key:'ga', iso639_1:'ga', iso639_2:'gle', name:'Irish', native:'Gaeilge', direction:'ltr' },
  { key:'cy', iso639_1:'cy', iso639_2:'cym', name:'Welsh', native:'Cymraeg', direction:'ltr' },
  { key:'is', iso639_1:'is', iso639_2:'isl', name:'Icelandic', native:'Íslenska', direction:'ltr' },
  { key:'sq', iso639_1:'sq', iso639_2:'sqi', name:'Albanian', native:'Shqip', direction:'ltr' },
  { key:'mk', iso639_1:'mk', iso639_2:'mkd', name:'Macedonian', native:'Македонски', direction:'ltr' },
  { key:'bs', iso639_1:'bs', iso639_2:'bos', name:'Bosnian', native:'Bosanski', direction:'ltr' },
  { key:'fo', iso639_1:'fo', iso639_2:'fao', name:'Faroese', native:'Føroyskt', direction:'ltr' },
  { key:'eu', iso639_1:'eu', iso639_2:'eus', name:'Basque', native:'Euskara', direction:'ltr' },
  { key:'ca', iso639_1:'ca', iso639_2:'cat', name:'Catalan', native:'Català', direction:'ltr' },
  { key:'gl', iso639_1:'gl', iso639_2:'glg', name:'Galician', native:'Galego', direction:'ltr' },
  { key:'mt', iso639_1:'mt', iso639_2:'mlt', name:'Maltese', native:'Malti', direction:'ltr' },
  { key:'lb', iso639_1:'lb', iso639_2:'ltz', name:'Luxembourgish', native:'Lëtzebuergesch', direction:'ltr' },
  { key:'gd', iso639_1:'gd', iso639_2:'gla', name:'Scottish Gaelic', native:'Gàidhlig', direction:'ltr' },
];

export const LANGUAGE_MAP = Object.fromEntries(LANGUAGES.map(l => [l.key, l]));
export const RTL_LANGUAGES = LANGUAGES.filter(l => l.direction === 'rtl').map(l => l.key);