// Master Life Goals Dataset — multi-select aspirations referenced by MemberProfile.life_goals.

export const LIFE_GOALS = [
  { key:'build_meaningful_friendships', label:'Build Meaningful Friendships' },
  { key:'meet_new_people', label:'Meet New People' },
  { key:'find_activity_partners', label:'Find Activity Partners' },
  { key:'expand_professional_network', label:'Expand My Professional Network' },
  { key:'improve_fitness', label:'Improve My Fitness' },
  { key:'improve_mental_wellbeing', label:'Improve My Mental Wellbeing' },
  { key:'healthier_lifestyle', label:'Live A Healthier Lifestyle' },
  { key:'travel_more', label:'Travel More' },
  { key:'explore_my_city', label:'Explore My City' },
  { key:'learn_new_skills', label:'Learn New Skills' },
  { key:'learn_new_languages', label:'Learn New Languages' },
  { key:'discover_new_hobbies', label:'Discover New Hobbies' },
  { key:'become_more_social', label:'Become More Social' },
  { key:'build_confidence', label:'Build Confidence' },
  { key:'find_creative_collaborators', label:'Find Creative Collaborators' },
  { key:'volunteer_more', label:'Volunteer More' },
  { key:'practice_mindfulness', label:'Practice Mindfulness' },
  { key:'work_life_balance', label:'Achieve Better Work-Life Balance' },
  { key:'start_a_business', label:'Start A Business' },
  { key:'grow_my_career', label:'Grow My Career' },
  { key:'find_a_mentor', label:'Find A Mentor' },
  { key:'become_a_mentor', label:'Become A Mentor' },
  { key:'join_community_activities', label:'Join Community Activities' },
  { key:'attend_more_events', label:'Attend More Events' },
  { key:'meet_people_from_different_cultures', label:'Meet People From Different Cultures' },
  { key:'spend_time_outdoors', label:'Spend More Time Outdoors' },
  { key:'reconnect_old_passions', label:'Reconnect With Old Passions' },
  { key:'become_more_adventurous', label:'Become More Adventurous' },
  { key:'create_lasting_memories', label:'Create Lasting Memories' },
  { key:'experience_different_cultures', label:'Experience Different Cultures' },
  { key:'enjoy_life_more', label:'Enjoy Life More' },
  { key:'achieve_financial_freedom', label:'Achieve Financial Freedom' },
  { key:'build_a_family', label:'Build A Family' },
  { key:'give_back_to_community', label:'Give Back To My Community' },
  { key:'live_mindfully', label:'Live More Mindfully' },
  { key:'read_more', label:'Read More Books' },
  { key:'stay_active', label:'Stay Active As I Age' },
  { key:'find_love', label:'Find A Meaningful Relationship' },
  { key:'overcome_social_anxiety', label:'Overcome Social Anxiety' },
  { key:'learn_to_cook', label:'Learn To Cook' },
];

export const LIFE_GOAL_MAP = Object.fromEntries(LIFE_GOALS.map((g) => [g.key, g]));