import React from 'react';
import { Rocket } from 'lucide-react';
import { MCSection } from '@/components/mission-control/ui';
import { useLocalization } from '@/lib/i18n/useLocalization';

const FUTURE = [
  { title: 'Revenue Intelligence', desc: 'Subscription revenue, MRR/ARR, and cohort revenue analysis.' },
  { title: 'Subscription Forecasting', desc: 'Projected renewals, churn, and revenue scenarios.' },
  { title: 'Predictive Growth', desc: 'ML-based member and engagement growth forecasts.' },
  { title: 'AI Business Forecasts', desc: 'Natural-language business outlook generated by AI.' },
  { title: 'Executive Forecasting', desc: 'Scenario planning for founders and leadership.' },
  { title: 'Investor Dashboard', desc: 'Curated metrics and trends for investor reporting.' },
];

/** FM-010 — Reserved space for future intelligence modules. */
export default function BiComingSoon() {
  const { t } = useLocalization();
  return (
    <MCSection icon={Rocket} title={t('mission.future_intelligence_modules')}>
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {FUTURE.map((f) => (
          <div key={f.title} className="rounded-xl border bg-card/60 p-4">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs px-2 py-0.5 rounded-full bg-warning/15 text-warning font-medium">{t('mission.coming_soon')}</span>
            </div>
            <h4 className="text-sm font-semibold">{f.title}</h4>
            <p className="text-xs text-muted-foreground mt-1">{f.desc}</p>
          </div>
        ))}
      </div>
    </MCSection>
  );
}